version: '3.4'

services:
  tallertechnologies.test.webui:
    container_name: webui
    image: ${DOCKER_REGISTRY-}tallertechnologiestestwebui
    build:
      context: .
      dockerfile: TallerTechnologies.Test.WebUI/Dockerfile
    ports: 8001:80

