insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (1, 'Cinda', 'Sains', 85, 'Chemical Engineer', 'Divorced');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (2, 'Audie', 'Hearns', 76, 'Paralegal', 'Married');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (3, 'Annaliese', 'Hannabuss', 29, 'Assistant Media Planner', 'Divorced');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (4, 'Ruperta', 'Lias', 62, 'Internal Auditor', 'Single');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (5, 'Reginauld', 'Kinton', 56, 'Senior Financial Analyst', 'Single');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (6, 'Monty', 'Varfalameev', 30, 'Chief Design Engineer', 'Widow/Widower');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (7, 'Wylie', 'Swyn', 87, 'Structural Engineer', 'Widow/Widower');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (8, 'Eddie', 'Lowth', 87, 'Safety Technician IV', 'Divorced');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (9, 'Dorry', 'Mordy', 44, 'Operator', 'Single');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (10, 'Cybil', 'Mellmer', 87, 'Office Assistant I', 'Married');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (11, 'Brooks', 'Mourant', 73, 'Technical Writer', 'Divorced');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (12, 'Rolf', 'Repp', 50, 'Help Desk Operator', 'Widow/Widower');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (13, 'Horace', 'Dametti', 54, 'Internal Auditor', 'Married');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (14, 'Luigi', 'Adamiec', 48, 'Sales Associate', 'Married');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (15, 'Claudianus', 'Duckett', 50, 'Recruiter', 'Married');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (16, 'Mellisa', 'Muzzlewhite', 26, 'Assistant Manager', 'Divorced');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (17, 'Vanna', 'Beattie', 35, 'Analog Circuit Design manager', 'Single');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (18, 'Brittney', 'Kitchingman', 69, 'Budget/Accounting Analyst III', 'Widow/Widower');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (19, 'Faythe', 'Whiskerd', 59, 'Executive Secretary', 'Single');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (20, 'Humfrey', 'Reichartz', 46, 'Staff Accountant III', 'Widow/Widower');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (21, 'Barnie', 'Steade', 82, 'Nuclear Power Engineer', 'Divorced');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (22, 'Tasha', 'Kinmond', 58, 'VP Quality Control', 'Widow/Widower');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (23, 'Arlene', 'Bearfoot', 19, 'Dental Hygienist', 'Widow/Widower');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (24, 'Carlyn', 'Janic', 69, 'Assistant Manager', 'Single');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (25, 'Far', 'Golds', 27, 'Sales Representative', 'Single');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (26, 'Johnnie', 'Winger', 34, 'Payment Adjustment Coordinator', 'Single');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (27, 'Justinn', 'Fitt', 79, 'Paralegal', 'Divorced');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (28, 'Mandy', 'Trembath', 32, 'Electrical Engineer', 'Divorced');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (29, 'Walt', 'Gairdner', 57, 'Dental Hygienist', 'Married');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (30, 'Clerc', 'Strewthers', 59, 'Software Engineer III', 'Divorced');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (31, 'Emmeline', 'Poyner', 86, 'Account Coordinator', 'Widow/Widower');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (32, 'Sterne', 'Patchett', 37, 'Engineer IV', 'Married');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (33, 'Corilla', 'Beevens', 88, 'Programmer Analyst IV', 'Single');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (34, 'Anderson', 'Pestor', 51, 'Senior Editor', 'Married');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (35, 'Brod', 'Slainey', 74, 'Operator', 'Divorced');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (36, 'Gordan', 'Ledekker', 57, 'Database Administrator I', 'Divorced');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (37, 'Harrie', 'Fieldgate', 29, 'Electrical Engineer', 'Divorced');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (38, 'Dorris', 'Claesens', 77, 'Quality Engineer', 'Single');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (39, 'Rolph', 'Basnett', 43, 'Developer IV', 'Widow/Widower');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (40, 'Tobie', 'Wohlers', 39, 'Data Coordiator', 'Married');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (41, 'Axe', 'Veall', 71, 'Assistant Media Planner', 'Single');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (42, 'Markus', 'Morecombe', 64, 'Junior Executive', 'Single');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (43, 'Corabella', 'Argrave', 34, 'Analyst Programmer', 'Divorced');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (44, 'Ferne', 'Caneo', 62, 'Safety Technician III', 'Widow/Widower');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (45, 'Deirdre', 'Beaton', 61, 'Quality Control Specialist', 'Widow/Widower');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (46, 'Agata', 'McVicker', 47, 'Dental Hygienist', 'Married');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (47, 'Raffarty', 'Peres', 34, 'VP Product Management', 'Divorced');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (48, 'Lalo', 'McMonies', 26, 'Speech Pathologist', 'Widow/Widower');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (49, 'Cynthia', 'Dunderdale', 80, 'Web Designer IV', 'Married');
insert into Customers (PersonID, FirstName, LastName, Age, Occupation, MartialStatus) values (50, 'Rees', 'Leatt', 58, 'Quality Engineer', 'Married');
